### ISSUE TITLE
Support for 32-bit applications

### ISSUE THREAD

**Issue by Apteryx0** [CatalystCode/windows-registry-node#38]
Hi,

I assume that windows-registry doesn't support 32-bit applications.... mainly because I kept getting ACCESS VIOLATIONS (C000 0005) until I changed the prototype of RegOpenKeyExA from uint64 to uint32. Assuming supporting both 32-bit and 64-bit is something that I can figure out, how do I go about contributing this?

Cheers,
Russell.

**Comment by Apteryx0** [comment]
Seem to have it working. I'll fork and create a pull request.

**Comment by ritazh** [comment]
Closed via 807408f
