### ISSUE TITLE
Delete a string value from a key?

### ISSUE THREAD

**Issue by a1diablo** [CatalystCode/windows-registry-node#50]
I see there is an option to delete a key but how to delete an individual value?

**Comment by a1diablo** [comment]
I've made a pull request regarding this change. #51

**Comment by robertohuertasm** [comment]
Let's hope this PR gets merged soon as this is a very useful feature! Thank you @abhimanyu-bst!

**Comment by ritazh** [comment]
Closed via #51

**Comment by VishwasShashidhar** [comment]
@ritazh Can we get a new release with this PR included in it please? Thanks!
