### ISSUE TITLE
Can't install this library using npm

### ISSUE THREAD

**Issue by amineamami** [CatalystCode/windows-registry-node#70]
When i want to install this library through npm i get this error :

C:\Users\username\node_modules\ref\src\binding.cc(644,1): warning C4996: 'Nan::ForceSet': a été déclaré déconseill
é [C:\Users\username\node_modules\ref\build\binding.vcxproj]
C:\Users\username\node_modules\nan\nan_maybe_43_inl.h(117): message : voir la déclaration de 'Nan::ForceSet' [C:\U
sers\username\node_modules\ref\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\username\node_modules\ref
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\username\package.json'
npm WARN username No description
npm WARN username No repository field.
npm WARN username No README data
npm WARN username No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by RupW** [comment]
I don't think this library is compatible with node 10+ sorry. There are a number of open PRs about this.
I don't recognise that specific error though.

**Comment by amineamami** [comment]
that worked. ty

**Comment by Spown** [comment]
why is this just closed? at least add
```json
  "engines": {
    "node": "<10"
  }
```
to the ``package.json``
